# Generated by Django 3.2.5 on 2021-07-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210704_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
